default:  fxctmp9_tmp\pp_vertexlit_and_unlit_generic_ps20.inc shaders\fxc\pp_vertexlit_and_unlit_generic_ps20.vcs fxctmp9_tmp\pp_vertexlit_and_unlit_generic_ps20b.inc shaders\fxc\pp_vertexlit_and_unlit_generic_ps20b.vcs fxctmp9_tmp\pp_vertexlit_and_unlit_generic_vs20.inc shaders\fxc\pp_vertexlit_and_unlit_generic_vs20.vcs

fxctmp9_tmp\pp_vertexlit_and_unlit_generic_ps20.inc shaders\fxc\pp_vertexlit_and_unlit_generic_ps20.vcs: pp_vertexlit_and_unlit_generic_ps2x.fxc common_flashlight_fxc.h common_vertexlitgeneric_dx9.h common_hlsl_cpp_consts.h common_ps_fxc.h common_pragmas.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." pp_vertexlit_and_unlit_generic_ps2x.fxc-----pp_vertexlit_and_unlit_generic_ps20
	echo pp_vertexlit_and_unlit_generic_ps2x.fxc>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

fxctmp9_tmp\pp_vertexlit_and_unlit_generic_ps20b.inc shaders\fxc\pp_vertexlit_and_unlit_generic_ps20b.vcs: pp_vertexlit_and_unlit_generic_ps2x.fxc common_flashlight_fxc.h common_vertexlitgeneric_dx9.h common_hlsl_cpp_consts.h common_ps_fxc.h common_pragmas.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." pp_vertexlit_and_unlit_generic_ps2x.fxc-----pp_vertexlit_and_unlit_generic_ps20b
	echo pp_vertexlit_and_unlit_generic_ps2x.fxc>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

fxctmp9_tmp\pp_vertexlit_and_unlit_generic_vs20.inc shaders\fxc\pp_vertexlit_and_unlit_generic_vs20.vcs: pp_vertexlit_and_unlit_generic_vs20.fxc common_hlsl_cpp_consts.h common_vs_fxc.h common_pragmas.h tree_sway.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." pp_vertexlit_and_unlit_generic_vs20.fxc-----pp_vertexlit_and_unlit_generic_vs20
	echo pp_vertexlit_and_unlit_generic_vs20.fxc>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo tree_sway.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

