default:  fxctmp9_tmp\pp_vertexlit_and_unlit_generic_ps30.inc shaders\fxc\pp_vertexlit_and_unlit_generic_ps30.vcs fxctmp9_tmp\pp_vertexlit_and_unlit_generic_vs30.inc shaders\fxc\pp_vertexlit_and_unlit_generic_vs30.vcs

fxctmp9_tmp\pp_vertexlit_and_unlit_generic_ps30.inc shaders\fxc\pp_vertexlit_and_unlit_generic_ps30.vcs: pp_vertexlit_and_unlit_generic_ps2x.fxc common_pragmas.h common_fxc.h common_ps_fxc.h common_hlsl_cpp_consts.h common_flashlight_fxc.h common_vertexlitgeneric_dx9.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." pp_vertexlit_and_unlit_generic_ps2x.fxc-----pp_vertexlit_and_unlit_generic_ps30
	echo pp_vertexlit_and_unlit_generic_ps2x.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt

fxctmp9_tmp\pp_vertexlit_and_unlit_generic_vs30.inc shaders\fxc\pp_vertexlit_and_unlit_generic_vs30.vcs: pp_vertexlit_and_unlit_generic_vs20.fxc common_vs_fxc.h tree_sway.h common_hlsl_cpp_consts.h common_fxc.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." pp_vertexlit_and_unlit_generic_vs20.fxc-----pp_vertexlit_and_unlit_generic_vs30
	echo pp_vertexlit_and_unlit_generic_vs20.fxc>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo tree_sway.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

